#!/usr/bin/env python

env = SConscript("godot-cpp/SConstruct")
env.Append(CPPPATH=["src"])

sources = Glob("src/*.cpp")
suffix = env["suffix"].replace(".dev", "").replace(".universal", "")
lib_filename = "{}smoke{}{}".format(
    env.subst("$SHLIBPREFIX"),
    suffix,
    env.subst("$SHLIBSUFFIX"),
)

library = env.SharedLibrary(
    "project/bin/{}".format(lib_filename),
    source=sources,
)

Default(library)
